"""add calibration_settings table

Revision ID: 1c165b4afcfa
Revises: d68463a9d9c1
Create Date: 2026-07-19 15:47:32.609952

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c165b4afcfa"
down_revision: Union[str, Sequence[str], None] = "d68463a9d9c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibration_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("anomaly_threshold", sa.Float(), nullable=False),
        sa.Column("churn_risk_alert_threshold", sa.Float(), nullable=False),
        sa.Column("auto_retrain_on_anomaly", sa.Boolean(), nullable=False),
        sa.Column(
            "digest_frequency", sa.Enum("DAILY", "WEEKLY", name="digest_frequency"), nullable=False
        ),
        sa.Column("digest_last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calibration_settings")
    # ### end Alembic commands ###
    # Postgres native Enum types survive table drop; must drop explicitly, or a
    # down-then-up cycle fails with "type digest_frequency already exists" (same
    # fix as run_status/retraining_status in earlier migrations).
    sa.Enum(name="digest_frequency").drop(op.get_bind(), checkfirst=True)
