"""add personas, simulation runs/steps, friction issues

Revision ID: 9e3926b19ab0
Revises: b9f1af37e8ba
Create Date: 2026-07-17 17:22:28.571147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e3926b19ab0"
down_revision: Union[str, Sequence[str], None] = "b9f1af37e8ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("baseline", sa.Boolean(), nullable=False),
        sa.Column("tech_affinity", sa.String(length=64), nullable=False),
        sa.Column("primary_device", sa.String(length=64), nullable=False),
        sa.Column("discovery_mode", sa.String(length=64), nullable=False),
        sa.Column("contextual_triggers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("technical_literacy", sa.Float(), nullable=False),
        sa.Column("anxiety", sa.Float(), nullable=False),
        sa.Column("patience", sa.Float(), nullable=False),
        sa.Column("curiosity", sa.Float(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personas_slug"), "personas", ["slug"], unique=True)
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flow_name", sa.String(length=200), nullable=False),
        sa.Column("goal", sa.String(length=500), nullable=False),
        sa.Column("persona_id", sa.Uuid(), nullable=False),
        sa.Column("screenshots_dir", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="run_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simulation_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("screen", sa.String(length=200), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["simulation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "friction_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("screen", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("heuristic_violated", sa.String(length=200), nullable=False),
        sa.Column("persona_impact", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["simulation_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["simulation_steps.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friction_issues")
    op.drop_table("simulation_steps")
    op.drop_table("simulation_runs")
    op.drop_index(op.f("ix_personas_slug"), table_name="personas")
    op.drop_table("personas")
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the native enum type it created for simulation_runs.status
    # (Postgres ENUMs are standalone types, not owned by the table) -- without this, a
    # later upgrade() fails with "type run_status already exists".
    sa.Enum(name="run_status").drop(op.get_bind(), checkfirst=True)
