"""add persona memories and retraining jobs

Revision ID: d68463a9d9c1
Revises: 5c42e91e976b
Create Date: 2026-07-18 17:54:03.429795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68463a9d9c1'
down_revision: Union[str, Sequence[str], None] = '5c42e91e976b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_memories_persona_id'), 'persona_memories', ['persona_id'], unique=False)
    op.create_table('retraining_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='retraining_status'), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('total_epochs', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retraining_jobs')
    op.drop_index(op.f('ix_persona_memories_persona_id'), table_name='persona_memories')
    op.drop_table('persona_memories')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the native enum type it created for retraining_jobs.status
    # (Postgres ENUMs are standalone types, not owned by the table) -- without this, a
    # later upgrade() fails with "type retraining_status already exists".
    sa.Enum(name='retraining_status').drop(op.get_bind(), checkfirst=True)
